#!/usr/bin/env python
#
# Usage: ./capture_put_slack http://example.com/ my-app my-bucket https://slack-incoming-webhook-url

import os
import sys
import json
import urllib
from datetime import datetime

capture_url = sys.argv[1]
base_name = sys.argv[2]
bucket_name = sys.argv[3]
slack_incoming_webhook_url = sys.argv[4]

job_url = os.environ.get('JOB_URL')

now = datetime.utcnow().strftime('%Y-%m-%d-%H-%M-%S')
file_name = '%s-%s.png' % (base_name, now)

script = ""
script += "var page = require('webpage').create();"
script += "page.open('%s', function(status) {" % capture_url
script += "  page.render('%s');" % file_name
script += "  phantom.exit();"
script += "});"

f = open('app.js', 'w')
f.write(script)
f.close()

os.system('phantomjs --ssl-protocol=any app.js')

os.system('s3cmd put %s s3://%s' % (file_name, bucket_name))

public_url = 'https://s3.amazonaws.com/%s/%s' % (bucket_name, file_name)
payload = json.dumps({'text': public_url})
os.system("curl -X POST --data-urlencode 'payload=%s' %s" % (payload, slack_incoming_webhook_url))

if job_url:
    payload = json.dumps({'text': job_url})
    os.system("curl -X POST --data-urlencode 'payload=%s' %s" % (payload, slack_incoming_webhook_url))
