#!/usr/bin/env python
#
# Usage: ./capture_put_slack http://example.com/ my-app my-bucket slack-token '#slack-channel' http://localhost/jenkins/job/...

import os
import sys
import urllib
from datetime import datetime

capture_url = sys.argv[1]
base_name = sys.argv[2]
bucket_name = sys.argv[3]
slack_token = sys.argv[4]
slack_channel = sys.argv[5]
job_url = sys.argv[6]

now = datetime.utcnow().strftime('%Y-%m-%d-%H-%M-%S')
file_name = '%s-%s.png' % (base_name, now)

script = ""
script += "var page = require('webpage').create();"
script += "page.open('%s', function(status) {" % capture_url
script += "  page.render('%s');" % file_name
script += "  phantom.exit();"
script += "});"

f = open('app.js', 'w')
f.write(script)
f.close()

os.system('phantomjs app.js')

os.system('s3cmd put %s s3://%s' % (file_name, bucket_name))

public_url = 'https://s3.amazonaws.com/%s/%s' % (bucket_name, file_name)
os.system("curl -d token=%s -d channel='%s' -d text=%s https://slack.com/api/chat.postMessage" % (slack_token, slack_channel, public_url))
os.system("curl -d token=%s -d channel='%s' -d text=%s https://slack.com/api/chat.postMessage" % (slack_token, slack_channel, urllib.quote(job_url)))
